package com.chun.nearanddear.domain.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Simple domain user model.
 */
@Serializable
data class User(
    val id: Long? = null, // Optional, auto-generated by Supabase
    @SerialName("created_at")
    val createdAt: String? = null, // Auto-managed by Supabase
    val name: String,
    val email: String,
    val phone: String? = null,
    @SerialName("avatar_url")
    val avatarUrl: String,
    val userID: String,
    @SerialName("updated_at") val updatedAt: String,
    @SerialName("userState")
    val userState: UserState = UserState.NORMAL,
    @SerialName("start_date") val startDate: String,
    @SerialName("end_date") val endDate: String
) {
    companion object {
        inline fun build(block: Builder.() -> Unit): User {
            return Builder().apply(block).build()
        }
    }

    class Builder {
        var id: Long? = null
        var createdAt: String? = null
        var name: String = ""
        var email: String = ""
        var phone: String? = null
        var avatarUrl: String = ""
        var userID: String = ""
        var updatedAt: String = ""
        var userState: UserState = UserState.NORMAL
        var startDate: String = ""
        var endDate: String = ""

        fun build(): User {
            return User(
                id = id,
                createdAt = createdAt,
                name = name,
                email = email,
                phone = phone,
                avatarUrl = avatarUrl,
                userID = userID,
                updatedAt = updatedAt,
                userState = userState,
                startDate = startDate,
                endDate = endDate
            )
        }
    }
}

@Serializable
enum class UserState {
    @SerialName("ADMIN") ADMIN,
    @SerialName("PREMIUM") PREMIUM,
    @SerialName("ANNUAL") ANNUAL,
    @SerialName("NORMAL") NORMAL
}
